"""
AURA Voice Agent — Shared Type Definitions
==========================================
Production-grade type definitions used across all voice-agent modules.

These types enforce consistent data shapes at module boundaries — callers
know exactly what keys a dict contains, and type checkers catch mismatches
before runtime.

Usage::

    from aura_types import ContentStats, WeeklyReport, TrackInfo

    def get_stats(person: str) -> ContentStats:
        return {"total_sessions": 5, ...}  # type checker verifies all keys
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import TypedDict


# ---------------------------------------------------------------------------
# Content Radar
# ---------------------------------------------------------------------------


class ContentStats(TypedDict):
    """Return type of ContentRadar.get_content_stats()."""

    sessions_per_week: float
    most_productive_day: str | None
    average_session_length: float
    days_since_last_session: int
    most_used_mode: str | None
    total_sessions: int
    total_minutes: float


# ---------------------------------------------------------------------------
# Energy Oracle
# ---------------------------------------------------------------------------


class WeeklyReportData(TypedDict):
    """Return type of EnergyOracle.get_weekly_data()."""

    automation_overrides: int
    scene_activations: dict[str, int]
    habit_summary: dict[str, bool]
    energy_patterns: dict[str, str]
    content_stats: ContentStats | None


# ---------------------------------------------------------------------------
# Ghost DJ
# ---------------------------------------------------------------------------


class MusicSuggestion(TypedDict):
    """Return type of GhostDJ._ask_claude_for_suggestion()."""

    playlist_uri: str
    reason: str
    mood: str
    energy_level: str


# ---------------------------------------------------------------------------
# Vibe Sync
# ---------------------------------------------------------------------------


class TrackInfo(TypedDict):
    """Current track info extracted from HA media_player attributes."""

    title: str
    artist: str
    album: str
    entity_id: str


class LightVibe(TypedDict):
    """Light settings generated by Claude for a track's mood."""

    color_rgb: tuple[int, int, int]
    brightness_pct: int
    transition_seconds: int


# ---------------------------------------------------------------------------
# Pulse Check
# ---------------------------------------------------------------------------


class DailyReport(TypedDict):
    """Return type of PulseCheck.get_daily_report()."""

    greeting: str
    habits_summary: str
    streak_highlights: str
    nudges: list[str]
    motivational_close: str


# ---------------------------------------------------------------------------
# AURA Drops
# ---------------------------------------------------------------------------


class EntitySnapshot(TypedDict):
    """Snapshot of a single HA entity for AURA Drops save/restore."""

    entity_id: str
    domain: str
    state: str
    attributes: dict[str, object]


class DropRecord(TypedDict):
    """A saved AURA Drop (scene snapshot)."""

    name: str
    display_name: str
    person: str
    created_at: str
    snapshot_count: int


# ---------------------------------------------------------------------------
# Social Sonar
# ---------------------------------------------------------------------------


class SocialModeResult(TypedDict):
    """Return type of SocialSonar.apply_social_mode()."""

    steps_completed: list[str]
    guest_count: int
    summary: str


# ---------------------------------------------------------------------------
# Deja Vu
# ---------------------------------------------------------------------------


class Prediction(TypedDict):
    """Return type of DejaVu.predict_next_scene()."""

    scene_name: str
    confidence: float
    reason: str
    entity_id: str


# ---------------------------------------------------------------------------
# Speaker Configuration
# ---------------------------------------------------------------------------


class SpeakerConfig(TypedDict):
    """Speaker configuration from voice-agent/config.yaml."""

    default: str
    rooms: dict[str, str]


# ---------------------------------------------------------------------------
# HA Entity State (Python-side mirror of the HA REST API shape)
# ---------------------------------------------------------------------------


class HAEntityState(TypedDict):
    """Shape of a single entity from GET /api/states/{entity_id}."""

    entity_id: str
    state: str
    attributes: dict[str, object]
    last_changed: str
    last_updated: str


# ---------------------------------------------------------------------------
# Voice Pipeline
# ---------------------------------------------------------------------------


class VoiceCommand(TypedDict):
    """Parsed voice command from the intent handler."""

    text: str
    person: str
    confidence: float
    timestamp: str


@dataclass(frozen=True)
class FeatureAction:
    """An action to execute on a feature module, parsed from Claude's response."""

    feature: str
    action: str
    params: dict[str, object]

    def __repr__(self) -> str:
        return f"FeatureAction({self.feature}.{self.action}, params={self.params})"
