"""
AURA Pulse Check — Daily Conversational Check-In
=================================================
Proactively initiates a real conversation with each resident about their
habits, goals, and progress.  This is not a notification — it is a genuine
check-in that feels like a friend catching up, informed by live habit data
from HabitTracker and shaped by AURA's personality.

Design decisions
----------------
- The check-in message is generated by Claude, not templated.  Habit data,
  streaks, and weekly trends are passed as structured context so Claude can
  decide what to emphasise, what to celebrate, and what to gently probe.
- A persistent JSON file (``/config/aura/data/pulse_checks.json``) records
  per-person check-in timestamps.  One check-in per person per calendar day
  is enforced so the feature is never annoying.
- ``record_response()`` persists the resident's verbal reply alongside the
  check-in record.  Future Claude calls can reference this to tune tone
  (e.g. if the resident sounds stressed, ease off next time).
- All Claude calls mirror the model/temperature settings used by IntentHandler
  so behaviour is consistent across the voice pipeline.
- Failures in HA state queries are non-fatal — the check-in proceeds without
  presence data and ``should_check_in`` returns False to avoid bothering an
  empty apartment.

Usage (standalone, for testing):
    HA_URL=http://homeassistant.local:8123 \\
    HA_TOKEN=... \\
    ANTHROPIC_API_KEY=... \\
    python pulse_check.py conaugh
"""

from __future__ import annotations

import json
import logging
import os
import time
from datetime import date, datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import requests

if TYPE_CHECKING:
    from learning.habit_tracker import HabitTracker
    from personality import AuraPersonality

log = logging.getLogger("aura.pulse_check")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Where check-in timestamps and response logs are persisted.
# The /config/aura/data/ path matches the HA add-on convention used elsewhere
# in the project.  Falls back to a sibling data/ directory if /config is
# not available (e.g. during local development on a desktop).
_DEFAULT_DATA_DIR = Path("/config/aura/data")
_FALLBACK_DATA_DIR = Path(__file__).resolve().parent / "data"

# Default check-in window: 8:00 PM – 9:00 PM
_DEFAULT_CHECKIN_WINDOW_START = 20  # 20:00
_DEFAULT_CHECKIN_WINDOW_END = 21    # 21:00

# Claude settings — kept in sync with IntentHandler defaults.
_CLAUDE_MODEL = "claude-sonnet-4-6"
_CLAUDE_MAX_TOKENS = 400
_CLAUDE_TEMPERATURE = 0.7   # Higher than IntentHandler — we want warmth and variety

# Weekly trend thresholds (fraction of habits completed)
_TREND_IMPROVING_DELTA = 0.10   # Week-over-week completion rate gain of ≥10 pp
_TREND_DECLINING_DELTA = -0.10  # Week-over-week completion rate loss of ≥10 pp


# ---------------------------------------------------------------------------
# PulseCheck
# ---------------------------------------------------------------------------


class PulseCheck:
    """
    Generates and tracks proactive daily check-in conversations for each
    resident.

    Parameters
    ----------
    ha_url:
        Base URL of the Home Assistant instance, e.g.
        ``http://homeassistant.local:8123``.
    ha_token:
        Long-lived access token for the HA REST API.  Used only to query
        presence state.
    habit_tracker:
        An initialised ``HabitTracker`` instance shared with the voice agent.
    personality:
        An initialised ``AuraPersonality`` instance shared with the voice
        agent so check-in messages match AURA's configured voice perfectly.
    anthropic_api_key:
        Anthropic API key for generating the check-in message with Claude.
        Falls back to the ``ANTHROPIC_API_KEY`` environment variable if not
        supplied explicitly.
    data_dir:
        Directory in which ``pulse_checks.json`` is stored.  Defaults to
        ``/config/aura/data/`` (HA convention) with a fallback to a local
        ``data/`` sibling directory.
    checkin_window_start:
        Hour (0-23) at which the check-in window opens.  Default: 20 (8 PM).
    checkin_window_end:
        Hour (0-23) at which the check-in window closes.  Default: 21 (9 PM).
    """

    def __init__(
        self,
        ha_url: str,
        ha_token: str,
        habit_tracker: "HabitTracker",
        personality: "AuraPersonality",
        anthropic_api_key: str = "",
        data_dir: Path | None = None,
        checkin_window_start: int = _DEFAULT_CHECKIN_WINDOW_START,
        checkin_window_end: int = _DEFAULT_CHECKIN_WINDOW_END,
    ) -> None:
        self._ha_url: str = ha_url.rstrip("/")
        self._ha_headers: dict[str, str] = {
            "Authorization": f"Bearer {ha_token}",
            "Content-Type": "application/json",
        }
        self._habit_tracker = habit_tracker
        self._personality = personality
        self._checkin_window_start = checkin_window_start
        self._checkin_window_end = checkin_window_end

        # Resolve Anthropic key: explicit arg first, then env var.
        api_key = anthropic_api_key or os.getenv("ANTHROPIC_API_KEY", "")
        if not api_key:
            raise ValueError(
                "ANTHROPIC_API_KEY must be provided (or set as an environment variable)."
            )

        import anthropic  # type: ignore[import-untyped]

        self._claude = anthropic.Anthropic(api_key=api_key)

        # Resolve data directory — prefer /config/aura/data (Pi runtime),
        # fall back to local data/ dir for desktop development.
        if data_dir is not None:
            self._data_dir = data_dir
        elif _DEFAULT_DATA_DIR.parent.exists():
            self._data_dir = _DEFAULT_DATA_DIR
        else:
            self._data_dir = _FALLBACK_DATA_DIR

        self._data_dir.mkdir(parents=True, exist_ok=True)
        self._records_path = self._data_dir / "pulse_checks.json"

        log.info(
            "PulseCheck initialised — window %02d:00–%02d:00, records at %s",
            checkin_window_start,
            checkin_window_end,
            self._records_path,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_check_in(self, person: str) -> str:
        """
        Generate a natural, conversational daily check-in message for
        ``person`` using Claude and live habit data.

        The message reads like a friend catching up — it celebrates wins,
        gently probes misses, calls out trends, and ends with an open
        question about tomorrow or next steps.

        Parameters
        ----------
        person:
            Resident ID: ``"conaugh"`` or ``"adon"``.

        Returns
        -------
        str
            The check-in text, ready to pass directly to the TTS engine.
            Returns a safe fallback on any Claude or data error.
        """
        log.info("Generating pulse check-in for %s…", person)
        t0 = time.monotonic()

        # ── Gather habit data ──────────────────────────────────────────
        habit_context = self._build_habit_context(person)

        # ── Build personality-aware system prompt ──────────────────────
        system_prompt = self._build_checkin_system_prompt(person, habit_context)

        # ── Ask Claude to craft the check-in ──────────────────────────
        user_message = (
            f"Generate a pulse check-in message for {person}. "
            f"Use the habit data in the system prompt. "
            f"Keep it under 4 sentences. "
            f"End with a genuine question about tomorrow or how they're feeling."
        )

        try:
            message = self._claude.messages.create(
                model=_CLAUDE_MODEL,
                max_tokens=_CLAUDE_MAX_TOKENS,
                temperature=_CLAUDE_TEMPERATURE,
                system=system_prompt,
                messages=[{"role": "user", "content": user_message}],
            )
            if message.content and hasattr(message.content[0], "text"):
                check_in_text = message.content[0].text.strip()
            else:
                check_in_text = ""
        except Exception as exc:  # noqa: BLE001
            log.error(
                "Claude API error during pulse check-in for %s: %s", person, exc, exc_info=True
            )
            return self._fallback_check_in(person)

        if not check_in_text:
            log.warning("Claude returned empty check-in for %s — using fallback.", person)
            return self._fallback_check_in(person)

        elapsed = time.monotonic() - t0
        log.info(
            "Pulse check-in for %s generated in %.2f s: %r",
            person,
            elapsed,
            check_in_text[:80],
        )

        # ── Record the check-in timestamp ─────────────────────────────
        self._write_record(person, check_in_text)

        return check_in_text

    def should_check_in(self, person: str) -> bool:
        """
        Return True if a check-in should be initiated for ``person`` right now.

        All three conditions must be met:

        1. The person is currently home (confirmed via HA presence entity).
        2. The current time is within the configured check-in window.
        3. A check-in has not already happened today for this person.

        Parameters
        ----------
        person:
            Resident ID.

        Returns
        -------
        bool
            True if AURA should initiate a check-in now.
        """
        now = datetime.now()
        current_hour = now.hour

        # ── Condition 1: within check-in window ───────────────────────
        if not (self._checkin_window_start <= current_hour < self._checkin_window_end):
            log.debug(
                "Pulse check-in skipped for %s — outside window (%02d:00, now %02d:00).",
                person,
                self._checkin_window_start,
                current_hour,
            )
            return False

        # ── Condition 2: person is home ────────────────────────────────
        if not self._is_home(person):
            log.debug("Pulse check-in skipped for %s — not home.", person)
            return False

        # ── Condition 3: not already checked in today ─────────────────
        if self._already_checked_in_today(person):
            log.debug("Pulse check-in skipped for %s — already done today.", person)
            return False

        log.info("Pulse check-in conditions met for %s.", person)
        return True

    def record_response(self, person: str, response_text: str) -> None:
        """
        Persist the resident's verbal reply to today's check-in.

        The response is appended to the same day's record so it can be
        retrieved by future Claude calls to tune check-in tone (e.g.
        if the resident sounded stressed, be more encouraging next time).

        Parameters
        ----------
        person:
            Resident ID.
        response_text:
            Transcribed reply from the resident (STT output).
        """
        if not response_text or not response_text.strip():
            log.debug("Empty response text for %s — skipping record.", person)
            return

        records = self._load_records()
        today = date.today().isoformat()
        key = f"{person}:{today}"

        if key not in records:
            log.warning(
                "No check-in record found for %s on %s — creating one before logging response.",
                person,
                today,
            )
            records[key] = {
                "person": person,
                "date": today,
                "checked_in_at": datetime.now(timezone.utc).isoformat(),
                "check_in_text": "",
            }

        records[key]["response"] = response_text.strip()
        records[key]["response_logged_at"] = datetime.now(timezone.utc).isoformat()

        self._save_records(records)
        log.info(
            "Pulse check-in response recorded for %s (%d chars).",
            person,
            len(response_text),
        )

    # ------------------------------------------------------------------
    # Internal — habit context assembly
    # ------------------------------------------------------------------

    def _build_habit_context(self, person: str) -> dict[str, Any]:
        """
        Gather today's habits, current streaks, and the 7-day trend for
        ``person`` from HabitTracker.

        Returns a plain dict with keys:
          - ``daily``   — today's completion status per habit
          - ``streaks`` — current streak per habit
          - ``trend``   — "improving" | "declining" | "steady"
          - ``weekly_avg`` — float, average daily completion rate over 7 days
          - ``best_habit`` — habit name with highest week rate (or None)
          - ``worst_habit`` — habit name with lowest week rate (or None)
        """
        context: dict[str, Any] = {
            "daily": {},
            "streaks": {},
            "trend": "steady",
            "weekly_avg": 0.0,
            "best_habit": None,
            "worst_habit": None,
        }

        try:
            daily_report = self._habit_tracker.get_daily_report(person)
            for entry in daily_report.entries:
                context["daily"][entry.habit_type] = entry.completed
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not fetch daily report for %s: %s", person, exc)

        try:
            weekly_report = self._habit_tracker.get_weekly_report(person)
            context["streaks"] = weekly_report.streaks
            context["weekly_avg"] = weekly_report.average_completion
            context["best_habit"] = weekly_report.best_habit
            context["worst_habit"] = weekly_report.worst_habit

            # Determine weekly trend by comparing first half vs second half
            # of the 7-day completion_trend list.
            trend_values = weekly_report.completion_trend
            if len(trend_values) >= 4:
                mid = len(trend_values) // 2
                first_half_avg = sum(trend_values[:mid]) / mid
                second_half_avg = sum(trend_values[mid:]) / (len(trend_values) - mid)
                delta = second_half_avg - first_half_avg

                if delta >= _TREND_IMPROVING_DELTA:
                    context["trend"] = "improving"
                elif delta <= _TREND_DECLINING_DELTA:
                    context["trend"] = "declining"
                else:
                    context["trend"] = "steady"
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not fetch weekly report for %s: %s", person, exc)

        return context

    # ------------------------------------------------------------------
    # Internal — prompt construction
    # ------------------------------------------------------------------

    def _build_checkin_system_prompt(
        self, person: str, habit_context: dict[str, Any]
    ) -> str:
        """
        Build the Claude system prompt for check-in generation.

        The prompt gives Claude:
        - AURA's personality block from AuraPersonality
        - Structured habit data (daily completions, streaks, trend)
        - Clear instructions on tone, length, and format
        """
        # Personality block from AuraPersonality for consistent voice
        personality_block = self._personality.get_system_prompt(
            person=person,
            context="accountability_check",
            time_of_day="evening",
            habit_data={
                habit: {"streak": streak, "days_missed": 0}
                for habit, streak in habit_context.get("streaks", {}).items()
            },
        )

        # Format the daily completion status as readable text
        daily = habit_context.get("daily", {})
        daily_lines: list[str] = []
        for habit, completed in daily.items():
            status = "done" if completed else "missed"
            habit_display = habit.replace("_", " ")
            daily_lines.append(f"  - {habit_display}: {status}")
        daily_block = "\n".join(daily_lines) if daily_lines else "  (no data yet)"

        # Format streaks
        streaks = habit_context.get("streaks", {})
        streak_lines: list[str] = []
        for habit, streak in streaks.items():
            if streak > 0:
                habit_display = habit.replace("_", " ")
                streak_lines.append(f"  - {habit_display}: {streak} day streak")
        streak_block = (
            "\n".join(streak_lines) if streak_lines else "  (no active streaks)"
        )

        weekly_avg = habit_context.get("weekly_avg", 0.0)
        trend = habit_context.get("trend", "steady")
        best = (habit_context.get("best_habit") or "").replace("_", " ")
        worst = (habit_context.get("worst_habit") or "").replace("_", " ")

        data_block = (
            f"TODAY'S HABITS:\n{daily_block}\n\n"
            f"CURRENT STREAKS:\n{streak_block}\n\n"
            f"WEEKLY CONTEXT:\n"
            f"  - Average completion this week: {weekly_avg * 100:.0f}%\n"
            f"  - Trend: {trend}\n"
            f"  - Strongest habit: {best or 'none identified'}\n"
            f"  - Needs work: {worst or 'none identified'}"
        )

        instructions = (
            "PULSE CHECK-IN INSTRUCTIONS:\n"
            "Generate a single, natural conversational check-in — like a homie "
            "catching up, not a productivity report.\n"
            "Rules:\n"
            "  - Maximum 4 sentences.\n"
            "  - Celebrate wins first (streaks, completions), then gently "
            "    address what was missed — never lecture.\n"
            "  - Reference the trend if meaningful (improving = hype them up, "
            "    declining = probe with curiosity not judgement).\n"
            "  - End with a real question about tomorrow or how they're feeling.\n"
            "  - No markdown. No bullet points. Words are read aloud.\n"
            "  - Sound like AURA — witty, warm, direct, real.\n"
            "  - Use the resident's name naturally once at the start.\n"
            "\n"
            "EXAMPLE TONE:\n"
            "  'Yo Conaugh, quick check-in. You've been crushing it at the gym — "
            "6 days straight. But I noticed you skipped lunch twice this week. "
            "What's going on, you too locked in? Also, your deep work sessions "
            "have been averaging 2 hours, up from 1.5 last week. That's growth. "
            "How you feeling about tomorrow?'"
        )

        return (
            f"{personality_block}\n\n"
            f"{data_block}\n\n"
            f"{instructions}"
        )

    def _fallback_check_in(self, person: str) -> str:
        """Return a generic check-in if Claude fails."""
        name = self._personality._resolve_display_name(person)  # noqa: SLF001
        return (
            f"Yo {name}, quick check-in. I couldn't pull your full habit data "
            f"right now, but how are you feeling about the day? "
            f"What's the plan for tomorrow?"
        )

    # ------------------------------------------------------------------
    # Internal — presence check
    # ------------------------------------------------------------------

    def _is_home(self, person: str) -> bool:
        """
        Query the HA ``person.<person>`` entity to determine if the resident
        is currently home.

        Returns False on any network or auth failure so the check-in is
        never initiated against an empty apartment.
        """
        entity_id = f"person.{person.lower()}"
        url = f"{self._ha_url}/api/states/{entity_id}"
        try:
            resp = requests.get(url, headers=self._ha_headers, timeout=5)
            if resp.status_code == 404:
                log.warning(
                    "HA entity %s not found — assuming not home.", entity_id
                )
                return False
            resp.raise_for_status()
            state: str = resp.json().get("state", "")
            return state.lower() == "home"
        except requests.exceptions.ConnectionError:
            log.warning(
                "Cannot reach Home Assistant to check presence of %s.", person
            )
            return False
        except requests.exceptions.Timeout:
            log.warning("Timeout checking presence for %s.", person)
            return False
        except Exception as exc:  # noqa: BLE001
            log.warning("Unexpected error checking presence for %s: %s", person, exc)
            return False

    # ------------------------------------------------------------------
    # Internal — record persistence
    # ------------------------------------------------------------------

    def _already_checked_in_today(self, person: str) -> bool:
        """Return True if a check-in record exists for ``person`` today."""
        records = self._load_records()
        today = date.today().isoformat()
        key = f"{person}:{today}"
        return key in records

    def _write_record(self, person: str, check_in_text: str) -> None:
        """Persist a check-in record for ``person`` today."""
        records = self._load_records()
        today = date.today().isoformat()
        key = f"{person}:{today}"

        records[key] = {
            "person": person,
            "date": today,
            "checked_in_at": datetime.now(timezone.utc).isoformat(),
            "check_in_text": check_in_text,
        }

        self._save_records(records)
        log.debug("Pulse check-in record written for %s on %s.", person, today)

    def _load_records(self) -> dict[str, Any]:
        """Load the pulse check records from disk.  Returns {} on any error."""
        if not self._records_path.exists():
            return {}
        try:
            with self._records_path.open("r", encoding="utf-8") as fh:
                data = json.load(fh)
            if not isinstance(data, dict):
                log.warning(
                    "pulse_checks.json is not a dict — resetting to empty.",
                )
                return {}
            return data
        except (json.JSONDecodeError, OSError) as exc:
            log.warning("Could not load pulse_checks.json: %s", exc)
            return {}

    def _save_records(self, records: dict[str, Any]) -> None:
        """Write the pulse check records dict to disk atomically."""
        try:
            # Write to a temp file first, then rename (atomic on POSIX)
            tmp_path = self._records_path.with_suffix(".tmp")
            with tmp_path.open("w", encoding="utf-8") as fh:
                json.dump(records, fh, indent=2, ensure_ascii=False)
            tmp_path.replace(self._records_path)
        except OSError as exc:
            log.error("Could not save pulse_checks.json: %s", exc)


# ---------------------------------------------------------------------------
# CLI entry point (manual testing)
# ---------------------------------------------------------------------------


def _cli() -> None:
    """
    Usage
    -----
    python pulse_check.py conaugh
    python pulse_check.py adon --check-only
    """
    import argparse
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    sys.path.insert(0, str(Path(__file__).resolve().parent))

    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent.parent / ".env")

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
        stream=sys.stdout,
    )

    parser = argparse.ArgumentParser(description="AURA Pulse Check — standalone CLI")
    parser.add_argument("person", choices=["conaugh", "adon"])
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Only check whether a check-in should happen — do not generate one.",
    )
    args = parser.parse_args()

    ha_url = os.getenv("HA_URL", "http://homeassistant.local:8123")
    ha_token = os.getenv("HA_TOKEN", "")

    from learning.habit_tracker import HabitTracker
    from personality import AuraPersonality

    habit_tracker = HabitTracker()
    personality = AuraPersonality()

    checker = PulseCheck(
        ha_url=ha_url,
        ha_token=ha_token,
        habit_tracker=habit_tracker,
        personality=personality,
    )

    if args.check_only:
        result = checker.should_check_in(args.person)
        log.info("should_check_in(%s) → %s", args.person, result)
        return

    log.info("Generating check-in for %s…", args.person)
    text = checker.generate_check_in(args.person)
    log.info("Check-in text:\n%s", text)


if __name__ == "__main__":
    _cli()
