"""
AURA Adaptive Learning — Pattern Engine
========================================
Three cooperating classes form the core of AURA's self-improving intelligence:

  PatternEngine    — records every relevant HA state change and mines
                     statistical patterns from the accumulated history.

  RoutineOptimizer — runs a Darwinian fitness loop on automations: high
                     override rate → poor fitness → mutation (parameter
                     adjustment).  Generates YAML suggestions for human
                     review and stores a generational history.

  ContextAwareness — maintains a live picture of what's happening in the
                     apartment right now (time of day, who's home, current
                     activity, weather) so every other system can make
                     smarter decisions without duplicating HA queries.

All persistent state lives in a single SQLite database whose path is read
from config.yaml (default: /config/aura/data/patterns.db).

Typical deployment
------------------
  The engine is imported and instantiated by a lightweight daemon (or an
  existing service such as clap_listener.py) that also subscribes to the
  HA WebSocket event stream.  On each relevant state-change event the daemon
  calls ``pattern_engine.record_event(...)``; a cron job or HA automation
  calls ``routine_optimizer.evolve()`` once a week.

Environment variables (from project .env)
------------------------------------------
  HA_URL   — base URL of the Home Assistant instance
  HA_TOKEN — long-lived access token for the HA REST API
"""

from __future__ import annotations

import fnmatch
import logging
import os
import sqlite3
import sys
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, time, timedelta, timezone
from enum import Enum
from pathlib import Path
from typing import Generator, Optional

import requests
import yaml
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    stream=sys.stdout,
)
log = logging.getLogger("aura.pattern_engine")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
CONFIG_PATH = SCRIPT_DIR / "config.yaml"
ENV_PATH = PROJECT_ROOT / ".env"

load_dotenv(ENV_PATH, override=False)

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class TimeOfDay(str, Enum):
    """Broad time-of-day category used throughout the learning system."""

    MORNING = "morning"       # 05:00 – 11:59
    MIDDAY = "midday"         # 12:00 – 13:59
    AFTERNOON = "afternoon"   # 14:00 – 17:59
    EVENING = "evening"       # 18:00 – 21:59
    NIGHT = "night"           # 22:00 – 04:59


class Activity(str, Enum):
    """Detected or inferred current apartment activity."""

    WORKING = "working"
    RELAXING = "relaxing"
    CREATING_CONTENT = "creating_content"
    EXERCISING = "exercising"
    SLEEPING = "sleeping"
    AWAY = "away"
    ENTERTAINING = "entertaining"
    UNKNOWN = "unknown"


class SuggestionStatus(str, Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ApartmentContext:
    """Immutable snapshot of current apartment context."""

    timestamp: datetime
    time_of_day: TimeOfDay
    day_of_week: int           # 0 = Monday … 6 = Sunday
    is_weekend: bool
    persons_home: list[str]    # person IDs currently marked 'home'
    activity: Activity
    weather_condition: str     # HA weather entity state string, e.g. 'sunny'
    temperature_outside: Optional[float]  # °C, None if unavailable


@dataclass
class PatternRecord:
    """Aggregated learned pattern for a single entity / hour / day slot."""

    entity_id: str
    day_of_week: int            # 0–6
    hour: int                   # 0–23
    avg_value: float            # numeric representation of the state
    confidence: float           # 0.0–1.0, derived from sample_count
    sample_count: int
    last_updated: datetime


@dataclass
class AutomationSuggestion:
    """A proposed change to an automation generated by RoutineOptimizer."""

    automation_id: str
    suggestion_type: str        # e.g. 'adjust_time', 'adjust_brightness'
    current_value: str
    suggested_value: str
    reason: str
    status: SuggestionStatus = SuggestionStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Database layer
# ---------------------------------------------------------------------------

_SCHEMA = """
CREATE TABLE IF NOT EXISTS events (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp     TEXT    NOT NULL,
    event_type    TEXT    NOT NULL,
    entity_id     TEXT    NOT NULL,
    old_state     TEXT,
    new_state     TEXT,
    triggered_by  TEXT    NOT NULL DEFAULT 'unknown',
    person        TEXT    NOT NULL DEFAULT 'unknown'
);

CREATE INDEX IF NOT EXISTS idx_events_entity
    ON events (entity_id, timestamp);

CREATE INDEX IF NOT EXISTS idx_events_triggered_by
    ON events (triggered_by, timestamp);

CREATE TABLE IF NOT EXISTS patterns (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id    TEXT    NOT NULL,
    day_of_week  INTEGER NOT NULL,
    hour         INTEGER NOT NULL,
    avg_value    REAL    NOT NULL DEFAULT 0.0,
    confidence   REAL    NOT NULL DEFAULT 0.0,
    sample_count INTEGER NOT NULL DEFAULT 0,
    last_updated TEXT    NOT NULL,
    UNIQUE (entity_id, day_of_week, hour)
);

CREATE TABLE IF NOT EXISTS automation_fitness (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    automation_id    TEXT    NOT NULL,
    generation       INTEGER NOT NULL DEFAULT 1,
    fitness_score    REAL    NOT NULL DEFAULT 1.0,
    override_count   INTEGER NOT NULL DEFAULT 0,
    activation_count INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL,
    UNIQUE (automation_id, generation)
);

CREATE TABLE IF NOT EXISTS suggestions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    automation_id   TEXT    NOT NULL,
    suggestion_type TEXT    NOT NULL,
    current_value   TEXT    NOT NULL,
    suggested_value TEXT    NOT NULL,
    reason          TEXT    NOT NULL,
    status          TEXT    NOT NULL DEFAULT 'pending',
    created_at      TEXT    NOT NULL
);
"""


class _Database:
    """
    Thin wrapper around a SQLite connection that enforces WAL mode (safe for
    concurrent readers from other services) and provides a context manager
    for transactional writes.
    """

    def __init__(self, db_path: str) -> None:
        path = Path(db_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self._path = str(path)
        self._ensure_schema()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._path, timeout=10, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.execute("PRAGMA foreign_keys=ON;")
        return conn

    def _ensure_schema(self) -> None:
        with self._connect() as conn:
            conn.executescript(_SCHEMA)
        log.info("Database ready at %s", self._path)

    @contextmanager
    def transaction(self) -> Generator[sqlite3.Connection, None, None]:
        """Yield an open connection inside an explicit transaction."""
        conn = self._connect()
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def execute(
        self, sql: str, params: tuple = ()
    ) -> list[sqlite3.Row]:
        """Read-only query; returns all rows."""
        with self._connect() as conn:
            cursor = conn.execute(sql, params)
            return cursor.fetchall()


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------


def _load_config() -> dict:
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Learning config not found: {CONFIG_PATH}")
    with CONFIG_PATH.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _ha_headers() -> dict[str, str]:
    token = os.getenv("HA_TOKEN", "")
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _ha_url(config: dict) -> str:
    return (os.getenv("HA_URL") or config["homeassistant"]["url"]).rstrip("/")


# ---------------------------------------------------------------------------
# PatternEngine
# ---------------------------------------------------------------------------


class PatternEngine:
    """
    Records Home Assistant state-change events and mines statistical patterns.

    Usage
    -----
    Instantiate once at service startup and keep the instance alive for the
    lifetime of the process.  Call ``record_event`` on every HA event you
    want tracked.  The engine handles its own SQLite writes; all operations
    are safe to call from a single-threaded async loop or a thread pool.

    Parameters
    ----------
    config_path:
        Optional override for the YAML config file path.  Defaults to the
        ``config.yaml`` sibling of this module.
    """

    # Entity states that carry a sensible numeric representation
    _BOOLEAN_MAP: dict[str, float] = {"on": 1.0, "off": 0.0, "home": 1.0, "not_home": 0.0}

    def __init__(self, config_path: Optional[Path] = None) -> None:
        if config_path is not None:
            with config_path.open("r", encoding="utf-8") as fh:
                self._config = yaml.safe_load(fh)
        else:
            self._config = _load_config()

        self._db = _Database(self._config["database"]["path"])
        self._tracked_patterns: list[str] = self._config["tracking"]["entities"]
        self._min_samples: int = int(self._config["tracking"]["min_samples"])
        log.info(
            "PatternEngine initialised — tracking patterns: %s",
            ", ".join(self._tracked_patterns),
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record_event(
        self,
        event_type: str,
        entity_id: str,
        old_state: Optional[str],
        new_state: Optional[str],
        triggered_by: str = "unknown",
        person: str = "unknown",
    ) -> None:
        """
        Persist a single HA state-change event and update the rolling pattern
        for the affected entity.

        Parameters
        ----------
        event_type:
            Arbitrary label such as 'state_changed', 'manual_override', or
            'scene_activated'.
        entity_id:
            Full HA entity ID, e.g. 'light.living_room_leds'.
        old_state:
            Previous state string from HA.  May be None for initial events.
        new_state:
            New state string from HA.
        triggered_by:
            One of: 'user', 'automation', 'scene', 'unknown'.
        person:
            Resident identifier ('conaugh', 'adon', 'unknown').
        """
        if not self._is_tracked(entity_id):
            return

        now = datetime.now(timezone.utc)
        ts = now.isoformat()

        with self._db.transaction() as conn:
            conn.execute(
                """
                INSERT INTO events
                    (timestamp, event_type, entity_id, old_state, new_state,
                     triggered_by, person)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (ts, event_type, entity_id, old_state, new_state, triggered_by, person),
            )

        # Update the rolling pattern aggregate for this entity / slot
        self._update_pattern(entity_id, new_state, now)

        log.debug(
            "Event recorded: %s  %s → %s  (by=%s, person=%s)",
            entity_id,
            old_state,
            new_state,
            triggered_by,
            person,
        )

    def get_patterns(
        self,
        entity_id: str,
        day_of_week: Optional[int] = None,
        time_range: Optional[tuple[int, int]] = None,
    ) -> list[PatternRecord]:
        """
        Return learned patterns for ``entity_id``, optionally filtered.

        Parameters
        ----------
        entity_id:
            Full HA entity ID.
        day_of_week:
            0 (Monday) – 6 (Sunday).  None returns all days.
        time_range:
            ``(start_hour, end_hour)`` inclusive.  None returns all hours.

        Returns
        -------
        list[PatternRecord]
            Only records with ``sample_count >= min_samples`` (from config)
            are returned so callers always get statistically reliable data.
        """
        conditions = ["entity_id = ?", "sample_count >= ?"]
        params: list[int | str] = [entity_id, self._min_samples]

        if day_of_week is not None:
            conditions.append("day_of_week = ?")
            params.append(day_of_week)

        if time_range is not None:
            start_h, end_h = time_range
            conditions.append("hour BETWEEN ? AND ?")
            params.extend([start_h, end_h])

        sql = (
            "SELECT * FROM patterns WHERE "
            + " AND ".join(conditions)
            + " ORDER BY day_of_week, hour"
        )
        rows = self._db.execute(sql, tuple(params))
        return [self._row_to_pattern(r) for r in rows]

    def get_suggestions(self) -> list[AutomationSuggestion]:
        """
        Return all pending automation suggestions from the database.  These
        are generated by ``RoutineOptimizer.evolve()`` and await human review.
        """
        rows = self._db.execute(
            "SELECT * FROM suggestions WHERE status = 'pending' ORDER BY created_at DESC"
        )
        return [self._row_to_suggestion(r) for r in rows]

    def get_current_context(self) -> ApartmentContext:
        """
        Build and return an ``ApartmentContext`` snapshot using the HA REST
        API.  Falls back gracefully when HA is unreachable.
        """
        now = datetime.now(timezone.utc)
        time_of_day = _classify_time_of_day(now)
        day = now.weekday()

        persons_home = self._query_persons_home()
        activity = self._infer_activity(now, persons_home)
        weather_condition, temp_outside = self._query_weather()

        return ApartmentContext(
            timestamp=now,
            time_of_day=time_of_day,
            day_of_week=day,
            is_weekend=day >= 5,
            persons_home=persons_home,
            activity=activity,
            weather_condition=weather_condition,
            temperature_outside=temp_outside,
        )

    def evolve(self) -> int:
        """
        Trigger the Darwinian optimisation cycle.  Delegates to
        ``RoutineOptimizer`` and returns the number of new suggestions
        generated.

        Also runs ``cleanup_old_events`` at the end of each cycle to prevent
        unbounded database growth.
        """
        optimizer = RoutineOptimizer(self._config, self._db)
        result = optimizer.evolve()
        self.cleanup_old_events()
        return result

    def cleanup_old_events(self, days: int = 90) -> int:
        """
        Delete events older than ``days`` days and reclaim disk space.

        Parameters
        ----------
        days:
            Retention window in days.  Events older than this are deleted.
            Defaults to 90 days.

        Returns
        -------
        int
            Number of rows deleted.
        """
        with self._db.transaction() as conn:
            cursor = conn.execute(
                "DELETE FROM events WHERE timestamp < datetime('now', ?)",
                (f"-{days} days",),
            )
            deleted = cursor.rowcount
            conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
        if deleted:
            log.info("Cleaned up %d events older than %d days", deleted, days)
        return deleted

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _is_tracked(self, entity_id: str) -> bool:
        """Return True if ``entity_id`` matches any tracked-entity glob pattern."""
        return any(fnmatch.fnmatch(entity_id, pat) for pat in self._tracked_patterns)

    def _update_pattern(
        self, entity_id: str, new_state: Optional[str], now: datetime
    ) -> None:
        """
        Incrementally update the rolling average for entity_id at the current
        day-of-week / hour slot using Welford's online algorithm so we never
        need to re-read all historical rows.
        """
        if new_state is None:
            return

        numeric = self._state_to_numeric(new_state)
        if numeric is None:
            return

        dow = now.weekday()
        hour = now.hour
        ts = now.isoformat()

        with self._db.transaction() as conn:
            row = conn.execute(
                "SELECT avg_value, sample_count FROM patterns "
                "WHERE entity_id = ? AND day_of_week = ? AND hour = ?",
                (entity_id, dow, hour),
            ).fetchone()

            if row is None:
                conn.execute(
                    """
                    INSERT INTO patterns
                        (entity_id, day_of_week, hour, avg_value, confidence,
                         sample_count, last_updated)
                    VALUES (?, ?, ?, ?, ?, 1, ?)
                    """,
                    (entity_id, dow, hour, numeric, 0.0, ts),
                )
            else:
                n = row["sample_count"] + 1
                # Welford incremental mean
                new_avg = row["avg_value"] + (numeric - row["avg_value"]) / n
                # Confidence saturates at 1.0 after min_samples * 4 events
                confidence = min(1.0, n / (self._min_samples * 4))
                conn.execute(
                    """
                    UPDATE patterns
                       SET avg_value    = ?,
                           confidence   = ?,
                           sample_count = ?,
                           last_updated = ?
                     WHERE entity_id = ? AND day_of_week = ? AND hour = ?
                    """,
                    (new_avg, confidence, n, ts, entity_id, dow, hour),
                )

    def _state_to_numeric(self, state: str) -> Optional[float]:
        """
        Convert a HA state string to a float for averaging.

        Returns None for states that have no sensible numeric form
        (e.g. 'unavailable', 'unknown').
        """
        lower = state.lower()
        if lower in self._BOOLEAN_MAP:
            return self._BOOLEAN_MAP[lower]
        try:
            return float(state)
        except ValueError:
            return None

    def _query_persons_home(self) -> list[str]:
        """
        Query the HA REST API for the state of each configured person entity.
        Returns person IDs (from config) that are currently 'home'.
        Falls back to an empty list if HA is unreachable.
        """
        persons_cfg: list[dict] = self._config.get("persons", [])
        base = _ha_url(self._config)
        headers = _ha_headers()
        home: list[str] = []

        for person in persons_cfg:
            entity = person.get("phone_entity", "")
            if not entity:
                continue
            try:
                resp = requests.get(
                    f"{base}/api/states/{entity}",
                    headers=headers,
                    timeout=4,
                )
                if resp.status_code == 200:
                    if resp.json().get("state") == "home":
                        home.append(person["id"])
            except requests.RequestException as exc:
                log.warning("Could not query %s from HA: %s", entity, exc)

        return home

    def _infer_activity(
        self, now: datetime, persons_home: list[str]
    ) -> Activity:
        """
        Infer the current apartment activity from presence data, time of day,
        and the most recent studio-mode boolean state stored in the DB.

        This is intentionally heuristic — it improves over time as the
        pattern database accumulates evidence.
        """
        if not persons_home:
            return Activity.AWAY

        time_of_day = _classify_time_of_day(now)

        # Studio mode boolean is a reliable signal for content creation
        rows = self._db.execute(
            """
            SELECT new_state FROM events
             WHERE entity_id = 'input_boolean.studio_mode_active'
             ORDER BY timestamp DESC
             LIMIT 1
            """
        )
        if rows and rows[0]["new_state"] == "on":
            return Activity.CREATING_CONTENT

        # Goodnight scene active → sleeping
        rows = self._db.execute(
            """
            SELECT new_state FROM events
             WHERE entity_id LIKE '%goodnight%'
               AND event_type = 'scene_activated'
             ORDER BY timestamp DESC
             LIMIT 1
            """
        )
        if rows and rows[0]["new_state"] == "on":
            # Only sleep if it's plausibly bedtime
            if time_of_day in (TimeOfDay.NIGHT, TimeOfDay.MORNING):
                return Activity.SLEEPING

        # Time-of-day heuristics
        if time_of_day == TimeOfDay.MORNING:
            return Activity.WORKING
        if time_of_day == TimeOfDay.MIDDAY:
            return Activity.WORKING
        if time_of_day == TimeOfDay.AFTERNOON:
            return Activity.WORKING
        if time_of_day == TimeOfDay.EVENING:
            return Activity.RELAXING
        if time_of_day == TimeOfDay.NIGHT:
            return Activity.RELAXING

        return Activity.UNKNOWN

    def _query_weather(self) -> tuple[str, Optional[float]]:
        """
        Retrieve weather condition and outside temperature from HA's weather
        entity.  Returns ('unknown', None) when HA is unreachable.
        """
        base = _ha_url(self._config)
        headers = _ha_headers()
        try:
            resp = requests.get(
                f"{base}/api/states/weather.home",
                headers=headers,
                timeout=4,
            )
            if resp.status_code == 200:
                data = resp.json()
                condition: str = data.get("state", "unknown")
                temp: Optional[float] = data.get("attributes", {}).get("temperature")
                return condition, temp
        except requests.RequestException as exc:
            log.warning("Weather query failed: %s", exc)
        return "unknown", None

    @staticmethod
    def _row_to_pattern(row: sqlite3.Row) -> PatternRecord:
        return PatternRecord(
            entity_id=row["entity_id"],
            day_of_week=row["day_of_week"],
            hour=row["hour"],
            avg_value=row["avg_value"],
            confidence=row["confidence"],
            sample_count=row["sample_count"],
            last_updated=datetime.fromisoformat(row["last_updated"]),
        )

    @staticmethod
    def _row_to_suggestion(row: sqlite3.Row) -> AutomationSuggestion:
        return AutomationSuggestion(
            automation_id=row["automation_id"],
            suggestion_type=row["suggestion_type"],
            current_value=row["current_value"],
            suggested_value=row["suggested_value"],
            reason=row["reason"],
            status=SuggestionStatus(row["status"]),
            created_at=datetime.fromisoformat(row["created_at"]),
        )


# ---------------------------------------------------------------------------
# RoutineOptimizer
# ---------------------------------------------------------------------------


class RoutineOptimizer:
    """
    Darwinian self-improvement engine for AURA automations.

    Each automation is modelled as an organism with a *fitness score*
    representing the fraction of activations that residents did NOT
    subsequently override.  High fitness → leave it alone.  Low fitness →
    mutate its parameters (time offsets, brightness levels, temperature
    set-points) and generate a YAML suggestion for human review.

    Generational history is preserved in ``automation_fitness`` so you can
    always see how an automation evolved and roll back to an earlier version.

    Parameters
    ----------
    config:
        Parsed learning config dict.
    db:
        Shared ``_Database`` instance (passed in from PatternEngine so both
        classes share the same on-disk file).
    """

    def __init__(self, config: dict, db: _Database) -> None:
        self._config = config
        self._db = db
        fitness_cfg = config.get("fitness", {})
        self._good_fitness: float = float(fitness_cfg.get("good_fitness", 0.8))
        self._poor_fitness: float = float(fitness_cfg.get("poor_fitness", 0.4))
        self._mutation_rate: float = float(fitness_cfg.get("mutation_rate", 0.1))

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record_activation(self, automation_id: str) -> None:
        """
        Increment the activation count for the current generation of
        ``automation_id``.  Call this from a HA automation trigger or
        the event listener whenever an automation fires.
        """
        self._upsert_fitness_row(automation_id)
        with self._db.transaction() as conn:
            conn.execute(
                """
                UPDATE automation_fitness
                   SET activation_count = activation_count + 1
                 WHERE automation_id = ?
                   AND generation = (
                       SELECT MAX(generation) FROM automation_fitness
                        WHERE automation_id = ?
                   )
                """,
                (automation_id, automation_id),
            )

    def record_override(self, automation_id: str) -> None:
        """
        Increment the override count for the current generation and
        recalculate fitness.  An override is any manual user action that
        reverses what an automation just did (e.g. turning lights back off
        within 2 minutes of an automation turning them on).
        """
        self._upsert_fitness_row(automation_id)
        with self._db.transaction() as conn:
            conn.execute(
                """
                UPDATE automation_fitness
                   SET override_count   = override_count + 1
                 WHERE automation_id = ?
                   AND generation = (
                       SELECT MAX(generation) FROM automation_fitness
                        WHERE automation_id = ?
                   )
                """,
                (automation_id, automation_id),
            )
            # Recompute fitness score in the same transaction
            row = conn.execute(
                """
                SELECT activation_count, override_count FROM automation_fitness
                 WHERE automation_id = ?
                   AND generation = (
                       SELECT MAX(generation) FROM automation_fitness
                        WHERE automation_id = ?
                   )
                """,
                (automation_id, automation_id),
            ).fetchone()

            if row and row["activation_count"] > 0:
                fitness = 1.0 - (row["override_count"] / row["activation_count"])
                conn.execute(
                    """
                    UPDATE automation_fitness
                       SET fitness_score = ?
                     WHERE automation_id = ?
                       AND generation = (
                           SELECT MAX(generation) FROM automation_fitness
                            WHERE automation_id = ?
                       )
                    """,
                    (fitness, automation_id, automation_id),
                )

    def get_fitness(self, automation_id: str) -> Optional[float]:
        """Return the current-generation fitness score for ``automation_id``."""
        rows = self._db.execute(
            """
            SELECT fitness_score FROM automation_fitness
             WHERE automation_id = ?
             ORDER BY generation DESC
             LIMIT 1
            """,
            (automation_id,),
        )
        return rows[0]["fitness_score"] if rows else None

    def evolve(self) -> int:
        """
        Run a full evolution cycle.

        1. Load all automation fitness records.
        2. Identify poor-fitness automations (score < ``poor_fitness``).
        3. For each poor-fitness automation, compute suggested mutations and
           write them to the ``suggestions`` table.
        4. Bump the generation counter for mutated automations.

        Returns the number of new suggestions created.
        """
        log.info("Starting Darwinian evolution cycle…")

        rows = self._db.execute(
            """
            SELECT af.automation_id,
                   af.generation,
                   af.fitness_score,
                   af.override_count,
                   af.activation_count
              FROM automation_fitness af
             INNER JOIN (
                 SELECT automation_id, MAX(generation) AS max_gen
                   FROM automation_fitness
                  GROUP BY automation_id
             ) latest ON af.automation_id = latest.automation_id
                     AND af.generation    = latest.max_gen
             WHERE af.activation_count >= 5
            """
        )

        suggestion_count = 0
        for row in rows:
            score: float = row["fitness_score"]
            automation_id: str = row["automation_id"]

            if score >= self._good_fitness:
                log.debug(
                    "%s — fitness %.2f ✓ healthy, no action needed", automation_id, score
                )
                continue

            if score < self._poor_fitness:
                log.info(
                    "%s — fitness %.2f below threshold (%.2f), generating mutations",
                    automation_id,
                    score,
                    self._poor_fitness,
                )
                n = self._generate_mutations(
                    automation_id=automation_id,
                    current_generation=row["generation"],
                    fitness_score=score,
                    override_count=row["override_count"],
                    activation_count=row["activation_count"],
                )
                suggestion_count += n
            else:
                log.info(
                    "%s — fitness %.2f marginal (%.2f–%.2f), monitoring",
                    automation_id,
                    score,
                    self._poor_fitness,
                    self._good_fitness,
                )

        log.info("Evolution cycle complete — %d suggestion(s) generated", suggestion_count)
        return suggestion_count

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _upsert_fitness_row(self, automation_id: str) -> None:
        """Ensure a current-generation fitness row exists for ``automation_id``."""
        with self._db.transaction() as conn:
            exists = conn.execute(
                """
                SELECT 1 FROM automation_fitness
                 WHERE automation_id = ?
                 LIMIT 1
                """,
                (automation_id,),
            ).fetchone()
            if not exists:
                conn.execute(
                    """
                    INSERT INTO automation_fitness
                        (automation_id, generation, fitness_score,
                         override_count, activation_count, created_at)
                    VALUES (?, 1, 1.0, 0, 0, ?)
                    """,
                    (automation_id, datetime.now(timezone.utc).isoformat()),
                )

    def _generate_mutations(
        self,
        automation_id: str,
        current_generation: int,
        fitness_score: float,
        override_count: int,
        activation_count: int,
    ) -> int:
        """
        Produce mutation suggestions for ``automation_id`` based on patterns
        in the events table.  Each suggestion is a YAML-friendly dict stored
        as strings in the ``suggestions`` table.

        Current mutation strategies
        ---------------------------
        * **time_shift** — If the automation fires at a fixed time but
          residents typically override it within a few minutes, suggest
          shifting the trigger time to match observed behaviour.
        * **brightness_adjust** — If lights are consistently manually
          adjusted after the automation sets them, suggest the observed
          preferred brightness level.
        * **new_generation** — Always bumps the generation counter so the
          next activation/override cycle is tracked fresh.

        Returns the number of suggestions written.
        """
        suggestions: list[dict] = []

        # --- Strategy 1: time shift ---
        time_suggestion = self._suggest_time_shift(automation_id, override_count)
        if time_suggestion:
            suggestions.append(time_suggestion)

        # --- Strategy 2: brightness correction ---
        brightness_suggestion = self._suggest_brightness(automation_id)
        if brightness_suggestion:
            suggestions.append(brightness_suggestion)

        # --- Fallback: generic tune suggestion if nothing specific found ---
        if not suggestions:
            suggestions.append(
                {
                    "suggestion_type": "review_required",
                    "current_value": f"fitness_score={fitness_score:.2f}",
                    "suggested_value": "manual_review",
                    "reason": (
                        f"Automation '{automation_id}' was overridden "
                        f"{override_count} of {activation_count} activations "
                        f"(fitness {fitness_score:.0%}).  No automatic mutation "
                        "strategy matched — manual review recommended."
                    ),
                }
            )

        ts = datetime.now(timezone.utc).isoformat()
        with self._db.transaction() as conn:
            for s in suggestions:
                conn.execute(
                    """
                    INSERT INTO suggestions
                        (automation_id, suggestion_type, current_value,
                         suggested_value, reason, status, created_at)
                    VALUES (?, ?, ?, ?, ?, 'pending', ?)
                    """,
                    (
                        automation_id,
                        s["suggestion_type"],
                        s["current_value"],
                        s["suggested_value"],
                        s["reason"],
                        ts,
                    ),
                )

            # Bump generation — the next activation starts a fresh cycle
            next_gen = current_generation + 1
            existing = conn.execute(
                "SELECT 1 FROM automation_fitness WHERE automation_id = ? AND generation = ?",
                (automation_id, next_gen),
            ).fetchone()
            if not existing:
                conn.execute(
                    """
                    INSERT INTO automation_fitness
                        (automation_id, generation, fitness_score,
                         override_count, activation_count, created_at)
                    VALUES (?, ?, 1.0, 0, 0, ?)
                    """,
                    (automation_id, next_gen, ts),
                )

        log.info(
            "%s — %d suggestion(s) written, bumped to generation %d",
            automation_id,
            len(suggestions),
            next_gen,
        )
        return len(suggestions)

    def _suggest_time_shift(
        self, automation_id: str, override_count: int
    ) -> Optional[dict]:
        """
        Look for manual overrides that happened shortly after this automation
        fired.  If found, compute the median gap and suggest shifting the
        automation time by that delta.
        """
        # Find events where this automation fired
        fired_rows = self._db.execute(
            """
            SELECT timestamp FROM events
             WHERE triggered_by = ?
               AND event_type = 'automation_fired'
             ORDER BY timestamp DESC
             LIMIT 50
            """,
            (automation_id,),
        )
        if len(fired_rows) < 3:
            return None

        gaps_minutes: list[float] = []
        for fired_row in fired_rows:
            fired_ts = datetime.fromisoformat(fired_row["timestamp"])
            window_end = (fired_ts + timedelta(minutes=10)).isoformat()

            override_rows = self._db.execute(
                """
                SELECT timestamp FROM events
                 WHERE triggered_by = 'user'
                   AND timestamp BETWEEN ? AND ?
                 ORDER BY timestamp ASC
                 LIMIT 1
                """,
                (fired_row["timestamp"], window_end),
            )
            if override_rows:
                override_ts = datetime.fromisoformat(override_rows[0]["timestamp"])
                gap = (override_ts - fired_ts).total_seconds() / 60.0
                gaps_minutes.append(gap)

        if len(gaps_minutes) < 3:
            return None

        # Median gap as the recommended shift
        sorted_gaps = sorted(gaps_minutes)
        median_gap = sorted_gaps[len(sorted_gaps) // 2]

        if abs(median_gap) < 1.0:
            return None  # Noise — not a meaningful shift

        direction = "later" if median_gap > 0 else "earlier"
        return {
            "suggestion_type": "time_shift",
            "current_value": "current_trigger_time",
            "suggested_value": f"shift_{direction}_{abs(median_gap):.0f}_minutes",
            "reason": (
                f"Residents consistently make manual adjustments approximately "
                f"{abs(median_gap):.0f} minutes {direction} than when "
                f"'{automation_id}' fires.  Shifting the trigger time "
                f"by {self._mutation_rate * 100:.0f}% of this gap per generation "
                "should reduce overrides."
            ),
        }

    def _suggest_brightness(self, automation_id: str) -> Optional[dict]:
        """
        Check whether lights are manually adjusted after this automation runs.
        If a consistent preferred brightness emerges, suggest it.
        """
        # Find light entities that this automation commonly affects
        fired_rows = self._db.execute(
            """
            SELECT timestamp FROM events
             WHERE triggered_by = ?
             ORDER BY timestamp DESC
             LIMIT 30
            """,
            (automation_id,),
        )
        if not fired_rows:
            return None

        brightness_values: list[float] = []
        for fired_row in fired_rows:
            window_end = (
                datetime.fromisoformat(fired_row["timestamp"]) + timedelta(minutes=5)
            ).isoformat()

            override_rows = self._db.execute(
                """
                SELECT new_state FROM events
                 WHERE triggered_by = 'user'
                   AND entity_id LIKE 'light.%'
                   AND timestamp BETWEEN ? AND ?
                 ORDER BY timestamp ASC
                 LIMIT 5
                """,
                (fired_row["timestamp"], window_end),
            )
            for r in override_rows:
                try:
                    pct = float(r["new_state"])
                    if 0.0 <= pct <= 100.0:
                        brightness_values.append(pct)
                except (ValueError, TypeError):
                    pass

        if len(brightness_values) < 5:
            return None

        avg_brightness = sum(brightness_values) / len(brightness_values)
        return {
            "suggestion_type": "brightness_adjust",
            "current_value": "automation_default_brightness",
            "suggested_value": f"{avg_brightness:.0f}_percent",
            "reason": (
                f"After '{automation_id}' activates, residents manually set light "
                f"brightness to an average of {avg_brightness:.0f}% across "
                f"{len(brightness_values)} observations.  Adopting this as the "
                "new default should eliminate the follow-up adjustment."
            ),
        }

    def generate_yaml_report(self) -> str:
        """
        Produce a human-readable YAML report of all pending suggestions.
        Intended for review via the voice agent or a dashboard card.

        Returns a YAML string ready to write to a file or display in a UI.
        """
        rows = self._db.execute(
            """
            SELECT s.*, af.generation, af.fitness_score
              FROM suggestions s
              LEFT JOIN automation_fitness af
                     ON s.automation_id = af.automation_id
              WHERE s.status = 'pending'
              ORDER BY s.created_at DESC
            """
        )

        report_data: list[dict] = []
        for row in rows:
            report_data.append(
                {
                    "automation_id": row["automation_id"],
                    "generation": row["generation"],
                    "fitness_score": row["fitness_score"],
                    "suggestion_type": row["suggestion_type"],
                    "current_value": row["current_value"],
                    "suggested_value": row["suggested_value"],
                    "reason": row["reason"],
                    "created_at": row["created_at"],
                }
            )

        return yaml.dump(
            {"aura_evolution_suggestions": report_data},
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )


# ---------------------------------------------------------------------------
# ContextAwareness
# ---------------------------------------------------------------------------


class ContextAwareness:
    """
    Maintains a live picture of what is happening in the apartment.

    This class is a thin convenience wrapper.  It holds a ``PatternEngine``
    instance and exposes context queries without requiring callers to
    instantiate ``PatternEngine`` directly.

    The context is rebuilt on every call to ``get_current_context`` — there
    is no caching, because Home Assistant state can change at any time.
    Callers that need a stable snapshot should store the returned
    ``ApartmentContext`` dataclass locally.
    """

    # Hour ranges that bound each TimeOfDay category (used by callers who
    # want to schedule tasks based on context categories).
    TIME_BOUNDARIES: dict[TimeOfDay, tuple[int, int]] = {
        TimeOfDay.MORNING: (5, 11),
        TimeOfDay.MIDDAY: (12, 13),
        TimeOfDay.AFTERNOON: (14, 17),
        TimeOfDay.EVENING: (18, 21),
        TimeOfDay.NIGHT: (22, 4),   # wraps midnight
    }

    def __init__(self, config_path: Optional[Path] = None) -> None:
        self._engine = PatternEngine(config_path=config_path)

    def get_current_context(self) -> ApartmentContext:
        """
        Return a fresh ``ApartmentContext`` snapshot.

        Convenience pass-through to ``PatternEngine.get_current_context()``.
        """
        return self._engine.get_current_context()

    def is_anyone_home(self) -> bool:
        """Return True if at least one resident is currently home."""
        context = self.get_current_context()
        return len(context.persons_home) > 0

    def get_active_residents(self) -> list[str]:
        """Return the list of resident IDs currently marked as home."""
        return self.get_current_context().persons_home

    def describe_context(self) -> str:
        """
        Return a single human-readable sentence summarising the current
        context.  Used by the voice agent to construct natural responses.

        Example output
        --------------
        "It's a Tuesday evening, Conaugh is home, and it looks like you're
        relaxing. Outside it's cloudy at 8°C."
        """
        ctx = self.get_current_context()
        config = self._engine._config  # noqa: SLF001 — intentional sibling access

        day_name = ctx.timestamp.strftime("%A")
        persons_cfg: list[dict] = config.get("persons", [])
        id_to_display = {p["id"]: p["display_name"] for p in persons_cfg}
        home_names = [id_to_display.get(pid, pid) for pid in ctx.persons_home]

        if not home_names:
            presence = "nobody is home"
        elif len(home_names) == 1:
            presence = f"{home_names[0]} is home"
        else:
            presence = f"{' and '.join(home_names)} are both home"

        activity_map = {
            Activity.WORKING: "you're in work mode",
            Activity.RELAXING: "you're relaxing",
            Activity.CREATING_CONTENT: "you're in content creation mode",
            Activity.EXERCISING: "you're exercising",
            Activity.SLEEPING: "everyone's asleep",
            Activity.AWAY: "the apartment is empty",
            Activity.ENTERTAINING: "you've got people over",
            Activity.UNKNOWN: "not sure what's going on",
        }
        activity_str = activity_map.get(ctx.activity, "doing something")

        weather_str = ""
        if ctx.weather_condition != "unknown":
            weather_str = f"  Outside it's {ctx.weather_condition}"
            if ctx.temperature_outside is not None:
                weather_str += f" at {ctx.temperature_outside:.0f}°C"
            weather_str += "."

        return (
            f"It's a {day_name} {ctx.time_of_day.value}, "
            f"{presence}, and {activity_str}.{weather_str}"
        )


# ---------------------------------------------------------------------------
# Standalone utilities
# ---------------------------------------------------------------------------


def _classify_time_of_day(dt: datetime) -> TimeOfDay:
    """
    Map a datetime to its ``TimeOfDay`` category.

    Night wraps past midnight (22:00 – 04:59).
    """
    h = dt.hour
    if 5 <= h <= 11:
        return TimeOfDay.MORNING
    if 12 <= h <= 13:
        return TimeOfDay.MIDDAY
    if 14 <= h <= 17:
        return TimeOfDay.AFTERNOON
    if 18 <= h <= 21:
        return TimeOfDay.EVENING
    return TimeOfDay.NIGHT  # 22:00–04:59


# ---------------------------------------------------------------------------
# CLI entry point — useful for testing the engine standalone on the Pi
# ---------------------------------------------------------------------------


def _cli() -> None:
    """
    Minimal CLI for running the evolution cycle or checking context from the
    command line.

    Usage
    -----
    python pattern_engine.py evolve
    python pattern_engine.py context
    python pattern_engine.py suggestions
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="AURA Pattern Engine — standalone CLI"
    )
    parser.add_argument(
        "command",
        choices=["evolve", "context", "suggestions"],
        help="Command to run",
    )
    args = parser.parse_args()

    engine = PatternEngine()

    if args.command == "evolve":
        n = engine.evolve()
        log.info("Evolution complete — %d suggestion(s) generated.", n)

    elif args.command == "context":
        ctx = engine.get_current_context()
        awareness = ContextAwareness()
        log.info("Context: %s", awareness.describe_context())
        log.info("Raw context: %s", ctx)

    elif args.command == "suggestions":
        suggestions = engine.get_suggestions()
        if not suggestions:
            log.info("No pending suggestions.")
        for s in suggestions:
            log.info(
                "[%s] %s → %s  (%s)",
                s.automation_id,
                s.current_value,
                s.suggested_value,
                s.reason,
            )


if __name__ == "__main__":
    _cli()
